### ISSUE TITLE
PlacePicker not precise

### ISSUE THREAD

**Issue by haldertaer** [suchoX/PlacePicker#21] opened 2019-08-27 12:23 UTC
When adding a pin while the map is zoomed out, the pin is added far away from its intended location, that's a real issue. Check out these images. 

Here, I placed the Picker on Mexico City:
![20190827_151215](https://user-images.githubusercontent.com/26697617/63770507-02fde780-c8de-11e9-966f-eef6354c3a3b.jpg)
But the pin appears far away from it:
![20190827_151300](https://user-images.githubusercontent.com/26697617/63770520-0abd8c00-c8de-11e9-89da-63b85c84eab9.jpg)

This isn't an issue when the map is really zoomed in. An update tackling this would be very much appreciated.

**Comment by PawelZarzycki** [comment] 2019-09-06 13:42
I opened similiar issue which was closed as intended behaviour which I dont agree with.

**Comment by suchoX** [comment] 2019-09-09 07:37
Let me see if I can improve this

**Comment by suchoX** [comment] 2019-10-20 08:38
@haldertaer @PawelZarzycki This was a very silly mistake on my part. The map marker was not precise coz the postion was taken of the middle of the Marker image rather than the tip of it. Just had to add the right bottom margin. Check out `1.0.0` and it should be fixed. Feel free to reopen it if not fixed.

**Closed by suchoX** 2019-10-20 08:38 UTC
