### ISSUE TITLE
Apply button not visible on selected phones

### ISSUE THREAD

**Issue by PawelZarzycki** [suchoX/PlacePicker#18] opened 2019-08-07 15:48 UTC
Hey!
Thanks for great lib, however I've tried your library on several phones and on some there is only the map and no apply button visible. Is this a known issue? 
1) Device OS version: 7.1.1
Device Model: Moto G Play
2)  Sony Xperia
3) Galaxy s7

![unnamed](https://user-images.githubusercontent.com/8467737/62637291-71810280-b93b-11e9-9a10-ff3a5b67b269.png)

**Comment by suchoX** [comment] 2019-08-08 08:23
@PawelZarzycki Definitely an issue. Need to look into it! Thanks for pointing out

**Comment by PawelZarzycki** [comment] 2019-08-08 08:33
> @PawelZarzycki Definitely an issue. Need to look into it! Thanks for pointing out

Thanks! Let me know your findings:)

**Comment by PawelZarzycki** [comment] 2019-08-12 07:49
Hey:)
Any news? Were you able to replicate the issue?

**Comment by suchoX** [comment] 2019-08-13 15:58
@PawelZarzycki I couldn't recreate the issue but created a method to disable bottomsheet animation. `disableBootomSheetAnimation(true)`. Keeping this open though

**Comment by PawelZarzycki** [comment] 2019-08-14 08:02
Can you invite me to contribute in the repo? I can make some improvements. 
You're thinking that disableBottomSheetAnimation works only on some API's (>23or so) and there is no fallback method?

**Comment by suchoX** [comment] 2019-08-20 12:21
@PawelZarzycki Just raise a PR to this library. I will review it and merge it. disableBottomSheetAnimation is a bandage honestly. I would rather find out what the issue is. I do not want to completely remove the animation as well.

**Comment by PawelZarzycki** [comment] 2019-08-20 12:24
I was able to reach someone who has the issue on his phone so I might be
able to investigate on my own. There's a bottom sheet but no button.

**Comment by suchoX** [comment] 2019-08-20 12:25
@PawelZarzycki Any help is welcome!

**Comment by PawelZarzycki** [comment] 2019-08-20 12:47
Here's a screenshot of the view with no tick-button visible. 
Please send me an email pawel.zarzycki1990@gmail.com and we can discuss it further. 
![Screenshot_2019-08-15-22-21-38](https://user-images.githubusercontent.com/8467737/63348279-3cbc7480-c359-11e9-8815-0ae42650fbfd.png)

**Comment by drmrbrewer** [comment] 2019-08-29 16:11
One of my app users has also just reported this:

![received_2384875551631835](https://user-images.githubusercontent.com/9009792/63957120-b7833f00-ca7f-11e9-931e-89ef675ceb66.png)

DEVICE
Device: M2 (HWMozart)
Manufacturer: Huawei 
Device type: Tablet 
Device language: French 
CPU make: HiSilicon 
CPU model: KIRIN930 
Native platform: armeabi-v7a, armeabi, arm64-v8a 
RAM (MB): 3072 
Screen size: 1200 × 1920 
Screen density (DPI): 320 
OpenGL ES version: 3.0 
OS: Android 5.1

**Comment by drmrbrewer** [comment] 2019-08-30 07:38
@PawelZarzycki @suchoX just wondering if you're working on this?

**Comment by PawelZarzycki** [comment] 2019-08-30 07:50
> @PawelZarzycki @suchoX just wondering if you're working on this?

I'm investigating but couldnt find any solution yet.

**Comment by suchoX** [comment] 2019-08-30 07:52
@drmrbrewer I am presently working on a solution where you can just have the option to disable the animation. That would solve the issue temporarily

**Comment by PawelZarzycki** [comment] 2019-08-30 07:58
Animation is a fix for the bottom sheet not showing at all I guess. For the user which have the button only missing I think we need to replace the button view with something more compatible. Don't you think?

**Comment by drmrbrewer** [comment] 2019-08-30 08:21
Both the bar and the button are animated (the button moves up and down too) so maybe it's something to try.

**Comment by drmrbrewer** [comment] 2019-09-10 21:42
Any progress on this?

**Comment by PawelZarzycki** [comment] 2019-10-18 08:46
Hey,
So I've finally managed to get my hands on an older device. The issue is with the layout_anchor, which is not working on lower than 21.  One and easy solution we can do is to put the button inside the bottom sheet in a constraint layout. I've attached screen. 

The other problem with bottom sheet not showing at all can be resolved by disabling the animation. 
If I find time I will create a PR, or you can just make the changes on your own. 
Many thanks for the awesome lib!

**Comment by suchoX** [comment] 2019-10-20 05:08
@PawelZarzycki Looks like Bottomsheet behavior is not working well with devices. Let me see. I will make the changes. Will notify you once its done and you can test it and let me know

**Comment by suchoX** [comment] 2019-10-20 08:40
@PawelZarzycki Competely re-did the UI removing BottomSheetBehavior in `1.0.0` and any form of animation. Now its a simple constraint layout. Closing this finally. Reopen it if the issue is not solved

**Closed by suchoX** 2019-10-20 08:40 UTC
Labels: help wanted

**Comment by drmrbrewer** [comment] 2019-10-20 18:16
@suchoX the user that had reported problems previously has confirmed that it is fixed for them with `1.0.0`.  Good job.
