### ISSUE TITLE
Just get blank non-scrollable map

### ISSUE THREAD

**Issue by drmrbrewer** [suchoX/PlacePicker#13] opened 2019-07-22 18:16 UTC
So far as I can tell, I've following the guide on the README completely, including adding the google API key to the app (it was already there, by virtue of using google's deprecated PlacePicker and also AutoComplete), but when I call `startActivityForResult()` I just get a blank map, with no apparent sign of life.  Hitting the tick FAB give a toast saying "Not a valid address".  

Any likely gotcha that I've fallen for?

**Comment by drmrbrewer** [comment] 2019-07-23 19:12
The key to getting it to work was to enable "Maps SDK for Android" in Google Cloud Platform.

**Comment by suchoX** [comment] 2019-07-26 14:21
Looks like the issue is solved. Closing it for now. Feel free to reopen it

**Closed by suchoX** 2019-07-26 14:21 UTC
